services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "mongo-data:/data/db"
    expose:
      - "27017"
  app:
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
volumes:
  mongo-data:
